
public class Habilidades {
	// EM ANDAMENTO, ATÉ QUINTA FAÇO E CONCERTO TUDO
	// O JOGO TA FUNCIONANDO, SÓ ALGUMAS COISAS DO METODO BATALHA QUE N TA SENDO EXECUTADO MAS CONCERTO ATÉ QUINTA
	// PODE DAR RUN NO MAIN SE QUISER TESTAR (Y)
}
